TRUNCATE TABLE Categories;
TRUNCATE TABLE ContentCategories;
TRUNCATE TABLE ContentTags;
TRUNCATE TABLE Posts;
TRUNCATE TABLE Products;
TRUNCATE TABLE SeoMeta;
TRUNCATE TABLE Tags;
TRUNCATE TABLE Users;